name: Get Wayback Machine Snapshots (Python) and Update README

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'スナップショットを取得するターゲットURL'
        required: true
        default: 'https://vol4records.com/music/%5BVL4-043%5Dhujikopro_-_chipbreak_is_dead.zip'

jobs:
  update_readme_with_snapshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用するPythonのバージョンを指定 (例: '3.9', '3.10', '3.x')

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script to fetch snapshots and update README
      id: run_python_script # このIDは outputs を参照するために必要
      run: |
        TARGET_URL="${{ github.event.inputs.target_url }}"

        if [ -z "$TARGET_URL" ]; then
          echo "Error: ターゲットURLが指定されていません。"
          exit 1
        fi

        python get_wayback_snapshots.py "$TARGET_URL"

        # README.mdが実際に変更されたか確認（変更がなければコミットしない）
        if git diff --quiet README.md; then
          echo "README.md に変更はありません。コミットをスキップします。"
          echo "changes_made=false" >> $GITHUB_OUTPUT
        else
          echo "README.md が更新されました。"
          echo "changes_made=true" >> $GITHUB_OUTPUT

        fi

    - name: Configure Git
      if: steps.run_python_script.outputs.changes_made == 'true'
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Commit and push README.md
      if: steps.run_python_script.outputs.changes_made == 'true'
      run: |
        git add README.md
        git commit -m "Update README.md with Wayback Machine snapshots for ${{ github.event.inputs.target_url }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
