name: Wayback Machine Archive List

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Target domain to archive'
        required: true
        type: string

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Get Wayback Machine archives
        run: |
          python -c '
          import requests
          import json
          import sys
          from datetime import datetime
          
          domain = "${{ github.event.inputs.domain }}"
          url = f"http://web.archive.org/cdx/search/cdx?url={domain}&output=json"
          
          try:
              response = requests.get(url)
              response.raise_for_status()
              data = response.json()
              
              # Skip the header row
              archives = data[1:]
              
              # Create markdown content
              content = f"# Wayback Machine Archives for {domain}\n\n"
              content += "Last updated: " + datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC") + "\n\n"
              content += "| Date | URL | Archive Link |\n"
              content += "|------|-----|---------------|\n"
              
              for archive in archives:
                  timestamp = archive[1]
                  original_url = archive[2]
                  date = datetime.strptime(timestamp, "%Y%m%d%H%M%S").strftime("%Y-%m-%d %H:%M:%S")
                  archive_url = f"https://web.archive.org/web/{timestamp}/{original_url}"
                  content += f"| {date} | {original_url} | [View Archive]({archive_url}) |\n"
              
              with open("README.md", "w", encoding="utf-8") as f:
                  f.write(content)
              
          except Exception as e:
              print(f"Error: {str(e)}")
              sys.exit(1)
          '
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update Wayback Machine archives for ${{ github.event.inputs.domain }}"
          git push
